public enum GameState
{
    MainMenu,
    FighterCreation,
    GymMap,
    GymSelection,
    GymScreen,
    Battle,
    Victory,
    Defeat,
    MovesScreen,
    StatsScreen,
    ShopScreen,
    Championship,
    AchievementsScreen,
    ProfileScreen,
    HallOfChampionsScreen,
    Settings,
    StreetFight
}
